/**
 * SBShop Spring Demo (SpringBoot-DEV1)
 * Kyouko is my waifu
 *
 * OpenAPI spec version: 1.0.0-Madoka-SpringBoot
 * Contact: incubator@dev1.madoka.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdminDTO } from './adminDTO';


/**
 * Profile API response: admin details
 */
export interface AdminResponse {
    /**
     * Object containing information for success response
     */
    data?: AdminDTO;
    /**
     * Any error or addtional message to be displayed
     */
    msg?: string;
    /**
     * Specific HTTP status code for API request
     */
    status: number;
}
