/**
 * SBShop Spring Demo (SpringBoot-DEV1)
 * Kyouko is my waifu
 *
 * OpenAPI spec version: 1.0.0-Madoka-SpringBoot
 * Contact: incubator@dev1.madoka.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AdminDTO {
    expireAt?: Date;
    id?: number;
    name?: string;
}
