/**
 * SBShop Spring Demo (SpringBoot)
 * Kyouko is my waifu
 *
 * OpenAPI spec version: 1.0.0boot
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Home/Internal API response
 */
export interface HomeResponse {
    /**
     * Object containing information for success response
     */
    data?: string;

    /**
     * Any error or addtional message to be displayed
     */
    msg?: string;

    /**
     * Specific HTTP status code for API request
     */
    status: number;

}
