/**
 * SBShop Spring Demo
 * Kyouko is my waifu
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Profile API response: multiple users
 */
export interface ProfileResponseUserList {
    /**
     * Object containing information for success response
     */
    data?: Array<models.UserDTO>;

    /**
     * Any error or addtional message to be displayed
     */
    msg?: string;

    /**
     * Specific HTTP status code for API request
     */
    status: number;

}
