/**
 * SBShop Spring Demo
 * Kyouko is my waifu
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface User {
    createdBy?: number;

    createdDate?: Date;

    modifiedBy?: number;

    modifiedDate?: Date;

    name?: string;

    nric?: string;

    userId?: number;

}
